def generate_default_observer_schema(app):
	"""
	Generate the default observer schema for each Kubernetes resource present in ``spec.manifest`` for which a custom observer schema hasn't been specified.
	"""
	for kind, spec in app.spec.manifest.items():
		if not hasattr(spec, 'observer_schema'):
			spec.observer_schema = {
				'kind': kind,
				'namespace': 'default',
				'observer': True,
				'observer_params': {},
				'observer_filters': [],
				'observer_labels': [],
				'observer_annotations': [],
				'observer_secrets': [],
				'observer_configmaps': [],
				'observer_services': [],
				'observer_pods': [],
				'observer_replication_controllers': [],
				'observer_endpoints': [],
				'observer_services_by_name': [],
				'observer_pods_by_name': [],
				'observer_replication_controllers_by_name': [],
				'observer_endpoints_by_name': [],
				'observer_services_by_label': [],
				'observer_pods_by_label': [],
				'observer_replication_controllers_by_label': [],
				'observer_endpoints_by_label': [],
				'observer_services_by_annotation': [],
				'observer_pods_by_annotation': [],
				'observer_replication_controllers_by_annotation': [],
				'observer_endpoints_by_annotation': [],
				'observer_services_by_selector': [],
				'observer_pods_by_selector': [],
				'observer_replication_controllers_by_selector': [],
				'observer_endpoints_by_selector': [],
				'observer_services_by_tag': [],
				'observer_pods_by_tag': [],
				'observer_replication_controllers_by_tag': [],
				'observer_endpoints_by_tag': [],
				'observer_services_by_tag_and_label': [],
				'observer_pods_by_tag_and_label': [],
				'observer_replication_controllers_by_tag_and_label': [],
				'observer_endpoints_by_tag_and_label': [],
				'observer_services_by_tag_and_annotation': [],
				'observer_pods_by_tag_and_annotation': [],
				'observer_replication_controllers_by_tag_and_annotation': [],
				'observer_endpoints_by_tag_and_annotation': [],
				'observer_services_by_tag_and_selector': [],
				'observer_pods_by_tag_and_selector': [],
				'observer_replication_controllers_by_tag_and_selector': [],
				'observer_endpoints