def base_config(user, etcd_host="localhost", etcd_port=2379):
	"""
	Creates a configuration with some simple parameters, the key parameters contains "tls", "authentication", "authorization", "etcd", "docs", and "log".
	"""
	return {
		"tls": False,
		"authentication": None,
		"authorization": None,
		"etcd": {
			"host": etcd_host,
			"port": etcd_port,
			"keyfile": None,
			"certfile": None,
			"cacertfile": None,
			"token": None,
			"token_ttl": 0,
			"token_leeway": 0,
			"token_renew_after": 0,
			"token_renew_before": 0,
			"token_renew_on": 0,
			"token_renew_on_failure": True,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0,
			"token_renew_on_failure_ttl": 0