def point_type(name, fields, srid_map):
	"""
	Dynamically Generating Point Class
	"""
	# Generate the class
	class_name = name.title()
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace('-', '')
	class_name = class_name.replace('_', '')
	class_name = class_name.replace('(', '')
	class_name = class_name.replace(')', '')
	class_name = class_name.replace('[', '')
	class_name = class_name.replace(']', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace(' ', '')
	class_name = class_name.replace